fix the issue when configuring remote MCP servers, hint for naming (#380)
# Description

fix the issue when configuring remote MCP servers (use the `mcp` instead
of `sse` as it tries to do a tls handshake), add a hint for incorrect
naming of remote servers + extract the actual errors, instead of showing
the JSON.

e.g.:

```
# Before
Error: failed to publish to registry: unexpected status: 400 Bad Request, {"title":"Bad Request","status":400,"detail":"Failed to create server","errors":[{"message":"remote URL https://servereverything.dev/mcp does not match namespace org/servereverything.dev: invalid namespace format: namespace must use reverse-DNS notation (e.g., \"dev.servereverything\" for servereverything.dev)"}]}

# After

Error: failed to publish to registry: 400 Bad Request: remote URL https://servereverything.dev/mcp does not match namespace org/servereverything.dev: invalid namespace format: namespace must use reverse-DNS notation (e.g., "dev.servereverything" for servereverything.dev)
```

# Change Type

```
/kind fix
```

# Changelog


```release-note
fix configuring/running remote MCP servers
```

---------

Signed-off-by: Peter Jausovec <peter.jausovec@solo.io>